name: Deploy Site

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: read-all

concurrency:
  group: deploy
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
        with:
          enablement: false

      - name: Install YQ
        uses: action-stars/install-tool-from-github-release@1fa61c3bea52eca3bcdb1f5c961a3b113fe7fa54 # v0.2.6
        with:
          github_token: ${{ github.token }}
          owner: mikefarah
          repository: yq
          extract: false
          filename_format: "{name}_{os}_{arch}"
          check_command: yq --version
          version: latest

      - name: Get Hugo version
        id: hugo_version
        run: echo "version=$(yq --unwrapScalar '.module.hugoVersion.min // "latest"' ./hugo.yaml)" >> "${GITHUB_OUTPUT}"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        with:
          hugo-version: ${{ steps.hugo_version.outputs.version }}
          extended: true

      - name: Build with Hugo
        run: |
          hugo \
            --gc \
            --minify \
            --environment production \
            --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ./public

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
